commonLabels:
  env: int

namePrefix: int-

bases:
  # you can also specify a Git repo URL here
  - ../../base

configMapGenerator:
  - name: microservice-configmap
    behavior: merge
    files:
      - microservice.properties
    literals:
      - DEFAULT_MESSAGE=Hello World INT.
      - PORT=8080
