commonLabels:
  env: prod

namePrefix: prod-

bases:
  # you can also specify a Git repo URL here
  - ../../base

patchesStrategicMerge:
  - microservice-replicas.yaml
  - microservice-healthcheck.yaml

configMapGenerator:
  - name: microservice-configmap
    behavior: merge
    files:
      - microservice.properties
    literals:
      - DEFAULT_MESSAGE=Hello World PROD.
      - PORT=8080
