commonLabels:
  env: dev

namePrefix: dev-

bases:
  # you can also specify a Git repo URL here
  - ../../base

configMapGenerator:
  - name: microservice-configmap
    behavior: merge
    files:
      - microservice.properties
    literals:
      - DEFAULT_MESSAGE=Hello World DEV.
      - PORT=8080
