apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: database
  name: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - name: database
          image: postgres:12.2-alpine
          imagePullPolicy: "IfNotPresent"
          envFrom:
            - configMapRef:
                name: database-configmap
          ports:
            - containerPort: 3306
