apiVersion: v1
kind: Service
metadata:
  name: productive-cloud-native-devex
  labels:
    env: local
spec:
  ports:
    - port: 8080
      name: http
  selector:
    app: productive-cloud-native-devex
